package com.fsquiroz.campsite.exception;

public enum ErrorCode {

    BR_MISSING_PARAM,
    BR_MALFORMED_PARAM,
    BR_MALFORMED_BODY,
    BR_INVALID_ID,
    BR_TEXT_TOO_LONG,
    BR_MODIFYING_CANCELLED,
    BR_INVALID_RANGE,
    BR_RANGE_NOT_ALLOWED_TOO_LOW,
    BR_RANGE_NOT_ALLOWED_TOO_HIGH,
    BR_ARRIVAL_TOO_EARLY,
    BR_NO_MORE_RESERVATION_AVAILABLE,
    NF_BY_ID,
    ISE
}
